version: "3"
services:
  keycloak:
    image: jboss/keycloak
    ports:
     - "9999:8080"
     - "8443:8443"
    environment:
      - KEYCLOAK_USER=admin 
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=H2
    volumes:
      - ./tls/:/opt/jboss/keycloak/standalone/configuration